<a href="https://colab.research.google.com/github/Muneebshah1192/Ai-Health-agent/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [2]:
import pandas as pd
import glob
import os
import numpy as np

# 1. Clone if not already cloned
if not os.path.exists('flyrank-ml-internship'):
    !git clone https://github.com/Muneebshah1192/flyrank-ml-internship.git

# 2. Search everywhere in the repository for ANY .csv file
data_files = glob.glob("flyrank-ml-internship/**/*.csv", recursive=True)

if not data_files:
    # If no CSV found, let's list the directories to see what's going on
    print("No CSV files found anywhere in the repo. Listing top-level contents:")
    print(os.listdir('flyrank-ml-internship'))
else:
    # Load the found CSV file
    file_path = data_files[0]
    print(f"Success! Found dataset at: {file_path}\n")
    df = pd.read_csv(file_path)

    print("--- UNIT OF ANALYSIS ---")
    print("One Row = One Webpage/URL over a specific timeframe.\n")

    # Display the actual dataframe structure
    display(df.head(3))

    print("\n--- TARGET COLUMN SKETCH ---")
    print("This is what our engineered target feature ('is_decaying') will look like:")

    # Create a mock target column to sketch the framing concept
    df_sketch = df.copy()
    df_sketch['is_decaying_target'] = np.random.choice([0, 1], size=len(df_sketch), p=[0.85, 0.15])

    # Show the relevant identifier column and the new target
    id_col = next((col for col in df.columns if 'url' in col.lower() or 'page' in col.lower() or 'path' in col.lower()), df.columns[0])
    display(df_sketch[[id_col, 'is_decaying_target']].head(5))

Success! Found dataset at: flyrank-ml-internship/data/raw/content_refresh_anonymized.csv

--- UNIT OF ANALYSIS ---
One Row = One Webpage/URL over a specific timeframe.

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9

--- TARGET COLUMN SKETCH ---
This is what our engineered target feature ('is_decaying') will look like:

   pageviews_90d  is_decaying_target
0             22                   0
1             10                   0
2             14                   0
3             87                   0
4            177                   0

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

**Lane:** Content Decay / Refresh Prioritization.

**Task Type:** Binary Classification.
The machine learning system will categorize existing pages into one of two distinct classes: `1` (Requires Immediate Refresh) or `0` (Stable/Healthy). This translates a continuous traffic problem into a clear, actionable flag for the editorial team.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

**The Proxy Target:** Since we cannot directly measure Google's internal ranking scores or algorithm shifts, we must use a proxy target derived from our own search data.

The target will be a binary label: `is_decaying`. We will define this as `1` if a page's average daily search impressions have dropped by more than 20% over the last 30 days compared to the previous 30-day period, and `0` otherwise.

## 3. Success metric

*One metric you can defend. What number means 'good'?*

**Success Metric:** Precision.

In this business context, the cost of a false positive is highly expensive—assigning an editor to update, rewrite, and QA a page that is naturally fluctuating but ultimately fine wastes hours of payroll. Therefore, we must optimize for Precision; when the model flags a page as decaying, we need to be highly confident that it genuinely needs human intervention.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [4]:
import pandas as pd
import glob
import os
import numpy as np

# 1. Clone if not already cloned
if not os.path.exists('flyrank-ml-internship'):
    !git clone https://github.com/Muneebshah1192/flyrank-ml-internship.git

# 2. Search everywhere in the repository for ANY .csv file
data_files = glob.glob("flyrank-ml-internship/**/*.csv", recursive=True)

if not data_files:
    # If no CSV found, let's list the directories to see what's going on
    print("No CSV files found anywhere in the repo. Listing top-level contents:")
    print(os.listdir('flyrank-ml-internship'))
else:
    # Load the found CSV file
    file_path = data_files[0]
    print(f"Success! Found dataset at: {file_path}\n")
    df = pd.read_csv(file_path)

    print("--- UNIT OF ANALYSIS ---")
    print("One Row = One Webpage/URL over a specific timeframe.\n")

    # Display the actual dataframe structure
    display(df.head(3))

    print("\n--- TARGET COLUMN SKETCH ---")
    print("This is what our engineered target feature ('is_decaying') will look like:")

    # Create a mock target column to sketch the framing concept
    df_sketch = df.copy()
    df_sketch['is_decaying_target'] = np.random.choice([0, 1], size=len(df_sketch), p=[0.85, 0.15])

    # Show the relevant identifier column and the new target
    id_col = next((col for col in df.columns if 'url' in col.lower() or 'page' in col.lower() or 'path' in col.lower()), df.columns[0])
    display(df_sketch[[id_col, 'is_decaying_target']].head(5))

Success! Found dataset at: flyrank-ml-internship/data/raw/content_refresh_anonymized.csv

--- UNIT OF ANALYSIS ---
One Row = One Webpage/URL over a specific timeframe.

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9

--- TARGET COLUMN SKETCH ---
This is what our engineered target feature ('is_decaying') will look like:

   pageviews_90d  is_decaying_target
0             22                   0
1             10                   0
2             14                   0
3             87                   0
4            177                   0

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

A fixed rule (e.g., "rewrite all pages older than 180 days" or "flag pages when CTR drops below 2%") is too rigid and highly inefficient. It ignores the nuanced reality of search dynamics: a 2-year-old, high-quality definitive guide might still be gaining traffic, while a 3-month-old trending article might be decaying rapidly. ML beats fixed heuristics here because it can learn the complex, non-linear interactions between content age, historical CTR trajectories, and impression volatility, allowing us to identify structural decay rather than just normal seasonal dips.

## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.